name: github-auto-green-bot

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "xkrivzooh@gmail.com"
          git config --local user.name "xkrivzooh"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.AUTO_GREEN_BOT }}@github.com/${{ github.repository }}
          git pull --rebase
          date +"%Y-%m-%d %H:%M:%S.%N" > useless.txt
          git commit -am "a commit every day, keep your girlfriend far away"
          git push
